export const LANDMARKS = {
  widgetScene: "widget-scene",
  widgetColumn: "widget-column",
  widgetLive: "widget-live",
  widgetCodex: "widget-codex",
  widgetGrok: "widget-grok",
  widgetSurface: "widget-surface",
  widgetSurfaceLive: "widget-surface-live",
  widgetSurfaceControls: "widget-surface-controls",
  widgetSurfaceOlder: "widget-surface-older",
  widgetSurfaceNewer: "widget-surface-newer",
  widgetSurfaceFollowLive: "widget-surface-follow-live",
  widgetSurfaceOpen: "widget-surface-open",
  widgetFeedScroll: "widget-feed-scroll",
  widgetFeedList: "widget-feed-list",
  widgetFeedStatus: "widget-feed-status",
  widgetFeedLiveToggle: "widget-feed-live-toggle",
  widgetFeedJumpLive: "widget-feed-jump-live",
  widgetFeedLoadEarlier: "widget-feed-load-earlier",
  widgetFeedOpenTranscript: "widget-feed-open-transcript",
  studioSessions: "studio-sessions",
  studioTimeline: "studio-timeline",
  studioSearch: "studio-search",
  studioInspector: "studio-inspector",
  studioTabEvent: "studio-tab-event",
  studioTabActivity: "studio-tab-activity",
  studioTabSources: "studio-tab-sources",
  studioTabSettings: "studio-tab-settings",
  studioExit: "studio-exit",
  studioBanner: "studio-banner",
} as const;

export type Landmark = (typeof LANDMARKS)[keyof typeof LANDMARKS];
